### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by alexgorbatchev**
This is a house cleaning patch, has the following:
- published to npm
- published to bower
- removes generated jison files from the repo
- uses build file to test
- switches tests to use mocha more common framework

### CODE REVIEW

**Comment by m93a** [comment]
I think this PR is worth looking into again. We found some critical security bugs and the fixes ought to be included in the NPM package.

**Comment by cshaa** [comment]
@alexgorbatchev Would you please look on this? You're the owner of the NPM module, so only you can update what's there. 12,106 people download the package *weekly*, all of that with critical bugs.

**Comment by cdauth** [comment]
I would really like to see this merged and to have an up-to-date version of filtrex that can be used through NPM. Would be willing to invest some work into it if maybe @joewalness could let me know what's missing for this to get merged (apart from rebasing).

**Comment by cshaa** [comment]
@joewalnes I think cdauth misspelled your username and you didn't get pinged. May we have your attention, please? :)

**Pull request closed without merging**
